# Generated by Django 4.2.7 on 2024-01-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_field', models.CharField(blank=True, max_length=50)),
                ('addresses_field', models.TextField(blank=True)),
                ('contact_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SiteFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(upload_to='logo/')),
                ('bottom_text', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link_address', models.CharField(max_length=50)),
            ],
        ),
    ]
