# Generated by Django 4.2.7 on 2024-01-31 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0012_remove_cartproductquantity_cart_and_more'),
        ('customer', '0004_customerprofile_remember_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CartProductQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='cart.CartProductQuantity', to='shop.product'),
        ),
        migrations.AddConstraint(
            model_name='cartproductquantity',
            constraint=models.UniqueConstraint(fields=('product', 'cart'), name='product_cart_constraint'),
        ),
    ]
